package com.kharcha.ledger.engine.classify

/**
 * Shared uppercase regexes. Every pattern here is matched against
 * [com.kharcha.ledger.engine.model.RawMessage.upperBody], which has already had
 * its whitespace collapsed — Indian SMS is full of stray newlines mid-sentence.
 */
internal object Patterns {

    val OTP = Regex(
        "\\b(OTP|O\\.T\\.P|ONE[ -]TIME[ -]PASSWORD|ONE TIME PIN|VERIFICATION CODE|SECURE CODE|3D ?SECURE)\\b"
    )
    val OTP_CODE = Regex("\\b\\d{4,8}\\b")
    val DO_NOT_SHARE = Regex("DO NOT SHARE|NEVER SHARE|DONT SHARE|SHARE IT WITH ANYONE")

    val DEBIT_VERB = Regex(
        "\\b(DEBITED|DEBIT|WITHDRAWN|SPENT|PAID|PAYMENT OF|SENT|TRANSFERRED|DEDUCTED|CHARGED|PURCHASE OF|TXN OF)\\b"
    )
    val CREDIT_VERB = Regex(
        "\\b(CREDITED|CREDIT|RECEIVED|DEPOSITED|ADDED TO|REFUNDED|REVERSED)\\b"
    )

    val FUTURE_TENSE = Regex("\\b(WILL BE|SHALL BE|IS DUE|DUE ON|WOULD BE|IS SCHEDULED|TO BE DEBITED)\\b")
    val MANDATE = Regex("\\b(E-?MANDATE|MANDATE|AUTOPAY|AUTO ?PAY|STANDING INSTRUCTION|SI )\\b")

    val FAILED = Regex(
        "\\b(COULD NOT BE PROCESSED|HAS FAILED|TRANSACTION FAILED|PAYMENT FAILED|WAS DECLINED|DECLINED|" +
            "UNSUCCESSFUL|NOT SUCCESSFUL|NOT PROCESSED|FAILED DUE TO|INSUFFICIENT (BALANCE|FUNDS)|TIMED OUT)\\b"
    )
    val REVERSAL = Regex(
        "\\b(REVERSED|REVERSAL|CREDITED BACK|ROLLED BACK|RETURNED TO YOUR ACCOUNT|" +
            "REFUND OF FAILED|FAILED TRANSACTION HAS BEEN)\\b"
    )
    val REFUND = Regex("\\b(REFUND|REFUNDED|REFUND OF|MONEY BACK)\\b")

    val BALANCE_LABEL = Regex(
        "\\b(AVL BAL|AVAIL(ABLE)? BAL(ANCE)?|AVL\\.? ?BAL|A/C BAL(ANCE)?|BAL(ANCE)? (IS|:)|CLEAR BAL|" +
            "TOTAL BAL(ANCE)?|CLOSING BAL(ANCE)?)\\b"
    )

    val STATEMENT = Regex(
        "\\b(STATEMENT|TOTAL AMOUNT DUE|TOTAL DUE|MIN(IMUM)? (AMOUNT )?DUE|MIN DUE|BILL (IS )?GENERATED|" +
            "E-?STATEMENT|OUTSTANDING (AMOUNT|BAL))\\b"
    )
    val CARD_BILL_PAYMENT = Regex(
        "\\b(PAYMENT (OF )?.{0,40}(RECEIVED|CREDITED|PROCESSED) (TOWARDS|FOR|AGAINST) (YOUR )?" +
            "(?:[A-Z]+ ){0,3}(CREDIT |DEBIT )?CARD|THANK YOU FOR (THE |YOUR )?PAYMENT|" +
            "CARD PAYMENT (OF|RECEIVED)|TOWARDS (YOUR )?(?:[A-Z]+ ){0,3}CREDIT CARD|" +
            "CREDIT CARD BILL PAYMENT|PAYMENT TOWARDS (?:[A-Z]+ ){0,3}CARD)\\b"
    )

    val ATM = Regex("\\b(ATM|CASH ?WITHDRAWAL|WITHDRAWN AT|CASH WDL|CASH WITHDRAWN|ATM CASH)\\b")

    val UPI = Regex("\\b(UPI|VPA|@[A-Z0-9.\\-]{2,}|BHIM|UPI ?REF|UPI ?ID)\\b")
    val IMPS = Regex("\\bIMPS\\b")
    val NEFT = Regex("\\bNEFT\\b")
    val RTGS = Regex("\\bRTGS\\b")
    val CARD = Regex("\\b(CREDIT CARD|DEBIT CARD|CARD ENDING|CARD NO|CARD XX|CARD ENDING WITH|" +
        "USING (YOUR )?CARD|ON (YOUR )?CARD|CC XX|POS)\\b")

    val SALARY = Regex("\\b(SALARY|SAL CR|SAL-|MONTHLY SALARY|PAYROLL|WAGES)\\b")
    val INTEREST = Regex("\\b(INTEREST (CREDITED|PAID)|INT\\.? CR|SAVINGS INTEREST|FD INTEREST)\\b")
    val CASHBACK = Regex("\\b(CASHBACK|CASH BACK|REWARD (CREDITED|POINTS CONVERTED))\\b")
    val EMI = Regex("\\b(EMI|LOAN INSTAL(L)?MENT|INSTAL(L)?MENT (OF|TOWARDS)|LOAN REPAYMENT|LOAN A/C)\\b")
    val INVESTMENT = Regex(
        "\\b(SIP|SYSTEMATIC INVESTMENT|MUTUAL FUND|MF PURCHASE|FOLIO|UNITS (ALLOT(TED)?|PURCHASED)|" +
            "NAV|PPF|NPS|RD INSTAL(L)?MENT|RECURRING DEPOSIT|FIXED DEPOSIT|FD BOOKED|DEMAT|EQUITY PURCHASE)\\b"
    )
    val BILL = Regex(
        "\\b(BILL ?PAY(MENT)?|BBPS|ELECTRICITY BILL|MOBILE RECHARGE|RECHARGE OF|DTH|POSTPAID BILL|" +
            "BROADBAND|GAS BILL|WATER BILL|UTILITY BILL|INSURANCE PREMIUM|PREMIUM OF)\\b"
    )

    val PROMOTIONAL = Regex(
        "\\b(OFFER|OFFERS|DISCOUNT|SALE|APPLY NOW|CLICK|HURRY|LIMITED PERIOD|PRE-?APPROVED|" +
            "CONGRATULATIONS|WIN |LUCKY|CASHBACK OFFER|DOWNLOAD (THE )?APP|T&C|TERMS AND CONDITIONS|" +
            "UNSUBSCRIBE|TO OPT ?OUT|EMI OPTION|LOWEST INTEREST|INSTANT LOAN|UPGRADE YOUR|ELIGIBLE FOR)\\b"
    )
    val URL = Regex("(HTTPS?://|WWW\\.|\\bBIT\\.LY\\b|\\bTINYURL\\b)")

    val ACCOUNT_HINT = Regex(
        "\\b(A/C|AC |ACCT|ACCOUNT|CARD|WALLET)\\s*(NO\\.?|NUMBER|ENDING( WITH)?|XX+|\\*+|#)?\\s*[X*#]*\\d{3,}"
    )
    val AMOUNT = Regex("(?:RS\\.?|INR|₹|MRP)\\s*\\d")
}
